config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nif, :name, 
      :surname1, :surname2, :address, :pc, :city, :province, 
      :phone1, :phone2, :email2, :suscriptor, :role_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to role_url(@role), notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to role_url(@role), notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.suscriptor = true

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :nif, :name, 
        :surname1, :surname2, :address, :pc, :city, :province, 
        :phone1, :phone2, :email2, :suscriptor, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">AppAlergenos</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Roles", roles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Usuarios", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Menus</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Platos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link">Ingredientes</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appalergenos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <!-- Boostrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render "layouts/navbar" %>
    <p style="color: green"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/roles/_form.html.erb
<div id="form" class="m-2 p-3">
  <%= form_with(model: @role) do |form| %>
    <% if @role.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

        <ul>
          <% @role.errors.each do |error| %>
          <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-lg-6 ml-2 mr-1">
        <%= form.label "Nombre", style: "display: block" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-lg-6 ml-2 mt-3">
        <%= form.submit "Guardar rol", class: "btn btn-sm btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/roles/_role.html.erb
<div id="<%= dom_id role %>"class="d-flex justify-content-between m-2 p-3 border-bottom">
  <h2><%= role.name %></h2>
  <div class="btn-group mx-3" role="group" aria-label="role Edit">
    <%= link_to edit_role_path, class: "btn btn-warning" do %>
      <%= fa_icon "exchange" , text: " Editar" %>
    <% end %>
    <%= button_to role_path(role), method: :delete, class: "btn btn-danger" do %>
      <%= fa_icon "trash" , text: " Eliminar" %>
    <% end %>
  </div>
</div>

app/views/roles/edit.html.erb
<div class="container-fluid d-flex justify-content-center ">
  <div class="col-6 m-2 p-3 bg-light rounded shadow">
    <div class="d-flex justify-content-between m-2 p-3 border-bottom">
      <h2>Editar rol</h2>
    </div>

    <%= render "form", role: @role %>

    <div id="page_navigation">
      <div class="row m-1 p-2">
        <%= link_to @role, class: "btn btn-info" do %>
          <%= fa_icon "eye", text: " Mostrar #{@role.name}" %>
        <% end %>
      </div>

      <div class="row m-1 p-2">
        <%= link_to roles_path, class: "btn btn-danger" do %>
          <%= fa_icon "undo", text: " Volver a Roles" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid d-flex justify-content-center ">
  <div class="col-6 bg-light rounded shadow">
    <div class="d-flex justify-content-between m-2 p-3 border-bottom">
      <h2>Roles</h2>
      <%= link_to new_role_path, class: "btn btn-success" do %>
      <%= fa_icon "plus", text: "Nuevo Rol" %>
      <% end %>
    </div>

    <div id="roles" class="col-6 d-block mx-auto m-2 p-3">
      <table>
        <thead>
          <tr>
            <td>Nombre</td>
            <td colspan="3">Acciones</td>
          </tr>
        </thead>
        <tbody>
          <% @roles.each do |role| %>
          <tr>
            <td><%= role.name %></td>
            <td colspan="3">
              <%= link_to role, class: "text-primary" do %>
                <%= fa_icon "eye", text: " Mostrar" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div id="page_navigation">
      <div class="row m-1 p-2">
        <%= link_to root_path, class: "btn btn-danger" do %>
          <%= fa_icon "home", text: " Página Principal" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/roles/new.html.erb
<div class="container-fluid d-flex justify-content-center ">
  <div class="col-6 m-2 p-3 bg-light rounded shadow">
    <div class="d-flex justify-content-between m-2 p-3 border-bottom">
      <h2>Nuevo Rol</h2>
    </div>

    <%= render "form", role: @role %>

    <div id="page_navigation">
      <div class="row m-1 p-2">
        <%= link_to roles_path, class: "btn btn-danger" do %>
          <%= fa_icon "arrow-left", text: " Volver a Roles" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/roles/show.html.erb
<%= render @role %>

app/views/users/_form.html.erb
<div id="form" class="m-2 p-3">
  <%= form_with(model: @user) do |form| %>
  <% if @user.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
      <% @user.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-lg-6 ml-2 mr-1">
      <%= form.label "Email", style: "display: block" %>
      <%= form.text_field :email, class: "form-control" %>
    </div>

    <% if @user.encrypted_password.blank? %>
    <div class="col-lg-6 mr-2 ml-1">
      <%= form.label "Password", style: "display: block" %>
      <%= form.text_field :password, class: "form-control" %>
    </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-6 col-lg-4 ml-2">
      <%= form.label "NIF", style: "display: block" %>
      <%= form.text_field :nif, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-lg-6 ml-2">
      <%= form.label "Nombre", style: "display: block" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  
    <div class="col-lg-6 ml-2 mr-1">
      <%= form.label "Apellido 1", style: "display: block" %>
      <%= form.text_field :surname1, class: "form-control" %>
    </div>
  
    <div class="col-lg-6 mr-2 ml-1">
      <%= form.label "Apellido 2", style: "display: block" %>
      <%= form.text_field :surname2, class: "form-control" %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-12 col-lg-6 ml-2">
      <%= form.label "Direccion", style: "display: block" %>
      <%= form.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-lg-6 ml-2">
      <%= form.label "Localidad", style: "display: block" %>
      <%= form.text_field :city, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 ml-2 mr-1">
      <%= form.label "Provincia", style: "display: block" %>
      <%= form.text_field :province, class: "form-control" %>
    </div>

    <div class="col-lg-6 mr-2 ml-1">
      <%= form.label "CP", style: "display: block" %>
      <%= form.text_field :pc, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-lg-4 ml-2">
      <%= form.label "Telefono 1", style: "display: block" %>
      <%= form.text_field :phone1, class: "form-control" %>
    </div>

    <div class="col-12 col-lg-4 ml-1 mr-1">
      <%= form.label "Telefono 2", style: "display: block" %>
      <%= form.text_field :phone2, class: "form-control" %>
    </div>

    <div class="col-12 col-lg-4 mr-2">
      <%= form.label "Email alternativo", style: "display: block" %>
      <%= form.text_field :email2, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-lg-6 ml-2">
      <%= form.label "Rol", style: "display: block" %>
      <%= form.collection_select :role_id, Role.all, :id, :name, 
      class: "form-select" %>
    </div> 
  </div>

  <div class="row">
    <div class="col-12 col-lg-6 ml-2 mt-3">
      <%= form.submit "Guardar Usuario", class: "btn btn-sm btn-primary" %>
    </div>
    <% end %>
  </div>

</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>"class="d-flex justify-content-between m-2 p-3 border-bottom">
  <h2><%= user.name %></h2>
  <div class="btn-group mx-3" role="group" aria-label="User Edit">
    <%= link_to edit_user_path, class: "btn btn-warning" do %>
      <%= fa_icon "exchange" , text: " Editar" %>
    <% end %>
    <%= button_to users_path, method: :delete, class: "btn btn-danger" do %>
      <%= fa_icon "trash" , text: " Eliminar" %>
    <% end %>
  </div>
</div>

<div id="<%= dom_id user %>" class="p-2">
  <ul class="row list-group list-group-horizontal m-2">
    <li class="col-12 list-group-item">
      <%= user.nif %>
    </li>
  </ul>
  <ul class="row list-group list-group-horizontal m-2">
    <li class="col-4 list-group-item"><%= user.name %></li>
    <li class="col-4 list-group-item"><%= user.surname1 %></li>
    <li class="col-4 list-group-item"><%= user.surname2 %></li>
  </ul>
  <ul class="row list-group list-group-horizontal m-2">
    <li class="col-10 list-group-item"><%= user.address %></li>
    <li class="col-2 list-group-item"><%= user.pc %></li>
  </ul>
  <div class="row list-group list-group-horizontal m-2">
    <li class="col-9 list-group-item"><%= user.city %></li>
    <li class="col-3 list-group-item"><%= user.province %></li>
  </div>
  <div class="row list-group list-group-horizontal m-2">
    <li class="col-4 list-group-item"><%= user.phone1 %></li>
    <li class="col-4 list-group-item"><%= user.phone2 %></li>
    <li class="col-4 list-group-item"><%= user.email2 %></li>
  </div>
  <div class="row list-group list-group-horizontal m-2">
    <% if user.suscriptor = true %>
      <li class="col-12 list-group-item bg-primary text-center text-white">Suscripción activa</li>
    <% else %>
      <li class="col-12 list-group-item bg-secondary text center text-white">No hay ninguna suscripción activa</li>
    <% end %>
  </div>

</div>

app/views/users/edit.html.erb
<div class="container-fluid d-flex justify-content-center ">
  <div class="col-6 m-2 p-3 bg-light rounded shadow">
    <div class="d-flex justify-content-between m-2 p-3 border-bottom">
      <h2>Editar usuario</h2>
    </div>

    <%= render "form", role: @user %>

    <div id="page_navigation">
      <div class="row m-1 p-2">
        <%= link_to @user, class: "btn btn-info" do %>
          <%= fa_icon "eye", text: " Mostrar #{@user.name}" %>
        <% end %>
      </div>

      <div class="row m-1 p-2">
        <%= link_to users_path, class: "btn btn-danger" do %>
          <%= fa_icon "undo", text: " Volver a Usuarios" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container-fluid d-flex justify-content-center">

  <div class="col-lg-8 col-md-10 bg-light rounded shadow">
    <div class="d-flex justify-content-between m-2 p-3 border-bottom">
      <h2>Usuarios</h2>
      <%= link_to new_user_path, class: "btn btn-success" do %>
      <%= fa_icon "plus", text: "Nuevo Usuario" %>
      <% end %>
    </div>

    <div id="usuarios" class="col-lg-8 d-block mx-auto m-2 p-3">
      <table>
        <thead>
          <tr>
            <td>Usuario</td>
            <td colspan="3">Acciones</td>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td>
              <%= link_to user, class: "btn btn-primary btn-sm" do %>
                <%= fa_icon "eye", text: " Mostrar" %>
              <% end %>
            </td>
            <td>
              <%= link_to edit_user_path(user), class: "btn btn-warning btn-sm" do %>
                <%= fa_icon "exchange", text: " Editar" %>
              <% end %>
            </td>
            <td>
              <%= button_to users_path(user), method: :delete, class: "btn btn-danger btn-sm" do %>
                <%= fa_icon "trash", text: " Eliminar" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div id="page_navigation">
      <div class="row m-1 p-2">
        <%= link_to root_path, class: "btn btn-dark" do %>
          <%= fa_icon "home", text: " Página Principal" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid d-flex justify-content-center ">
  <div class="col-6 m-2 p-3 bg-light rounded shadow">
    <div class="d-flex justify-content-between m-2 p-3 border-bottom">
      <h2>Nuevo Usuario</h2>
    </div>

    <%= render "form", user: @user %>

    <div id="page_navigation">
      <div class="row m-1 p-2">
        <%= link_to users_path, class: "btn btn-danger" do %>
          <%= fa_icon "arrow-left", text: " Volver a Usuarios" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid d-flex justify-content-center ">
  <div class="col-lg-6 col-10 m-2 p-3 bg-light rounded shadow">
    <%= render @user %>
    <div class="rounded shadow p-3">
    </div>
    <div id="page_navigation">
      <div class="row m-1 p-2">
        <%= link_to users_path, class: "btn btn-dark" do %>
          <%= fa_icon "undo", text: " Volver a Usuarios" %>
        <% end %>
      </div>
    </div>
  </div>